"""File with GUI labels"""

labels = {
    "en": {
        "active_vault": "ACTIVE VAULT",
        "add_log_entry": "ADD LOG ENTRY",
        "add_new_vault": "ADD NEW VAULT",
        "back": "BACK",
        "cancel": "CANCEL",
        "date": "DATE",
        "create_new_vault": "CREATE NEW VAULT",
        "delete_entry": "DELETE ENTRY",
        "delete_entry_confirmation": "Are you sure you want to delete this entry?",
        "delete_user": "DELETE USER",
        "delete_vault": "DELETE VAULT",
        "delete_vault_confirmation": "Are you sure you want to delete this vault and all associated log entries?",
        "entry_prefix": "ENTRY #",
        "gm_error": "HINT: What's the name of the game?",
        "closed": "CLOSED",
        "ok": "OK",
        "open": "OPEN",
        "door_status": "DOOR STATUS",
        "edit": "EDIT",
        "enter": "ENTER",
        "entry": "ENTRY",
        "exit": "EXIT",
        "env_sensors": "ENVIRONMENTAL SENSORS: OFFLINE",
        "log_entries": "LOG ENTRIES",
        "login": "LOGIN",
        "logout": "LOGOUT",
        "monitoring": "MONITORING: OFFLINE",
        "password": "PASSWORD",
        "population": "VAULT POPULATION",
        "save": "SAVE",
        "selection": "SELECT AN ENTRY TO SEE DETAILS",
        "vault": "VAULT",
        "vault_management": "VAULT MANAGEMENT",
        "vault_update": "UPDATE VAULT",
        "vault_updated": "Vault updated successfully.",
        "no_vaults": "NO VAULTS IN THE SYSTEM",
        "status": "VAULT STATUS",
        "security_level": "SECURITY LEVEL",
        "title": "TITLE",
        "overseer": "OVERSEER",
        "overseer_access": "OVERSEER ACCESS",
        "yes": "YES",
        "no_active_vault": "No active vault found. Log in as Game Master and activate one.",
        "no_active_vault_short": "No active vault found.",
        "num_value_error": "Enter a valid number.",
        "unauthorized_access": "You are not authorized to access this vault.",
        "active": "ACTIVE",
        "inactive": "INACTIVE",
        "select": "select",
        "not_empty": "This field cannot be empty",
        "vault_exists": "Vault with this number already exists.",
        "problem_loading_data": "Problem loading data.",
        "incorrect_data": "Enter correct data"

    }
}
